[package]
name = "i24"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.16.1"
num-traits = "0.2.19"

pyo3 = { version = "0.21.2", features = ["extension-module"], optional = true }
numpy = { version = "0.21.0", optional = true }

[features]
pyo3 = ["dep:pyo3", "dep:numpy"]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
panic = "abort"
strip = true
