[package]
name = "i24"
version = "1.0.0"
edition = "2021"
license = "MIT"
license-file = "LICENSE"
description = "A Rust library for working with 24-bit integers."
readme = "README.md"
repository = "https://github.com/jmg049/i24"
documentation = "https://docs.rs/i24"
categories = ["data-structures", "math", "numerics"]

[dependencies]
bytemuck = "1.16.1"
num-traits = "0.2.19"

pyo3 = { version = "0.21.2", features = ["extension-module"], optional = true }
numpy = { version = "0.21.0", optional = true }

[features]
pyo3 = ["dep:pyo3", "dep:numpy"]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
panic = "abort"
strip = true
